#!/bin/bash
"""
运行API网关服务
"""

# 设置环境变量
export OBJC_DISABLE_INITIALIZE_FORK_SAFETY=YES
export PYTORCH_ENABLE_MPS_FALLBACK=1
export MPS_HIGH_WATERMARK_RATIO=0.5
export PYTORCH_MPS_HIGH_WATERMARK_RATIO=0.5
export TORCH_MPS_HIGH_WATERMARK_RATIO=0.5
export OMP_NUM_THREADS=1
export MKL_NUM_THREADS=1
export OPENBLAS_NUM_THREADS=1
export VECLIB_MAXIMUM_THREADS=1
export NUMEXPR_NUM_THREADS=1
export KMP_DUPLICATE_LIB_OK=TRUE

# 切换到脚本所在目录
cd "$(dirname "$0")"

# 运行API网关服务
python3 app.py --host 0.0.0.0 --port 8080 --workers 1
