#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
生成采集配置文件：
1. 从 keywords 目录读取所有角色名
2. 生成 CHARACTER_MAP 和 KEYWORD_GAME_MAP 的 JSON 文件
"""

import os
import json
from pathlib import Path

PROJECT_ROOT = Path(__file__).parent.parent.parent.parent
KEYWORD_DIR = PROJECT_ROOT / "archived" / "auto_spider_img" / "keywords"
CONFIG_DIR = Path(__file__).parent

GAME_TAG_MAP = {
    "genshin": "genshin_impact",
    "star_rail": "honkai:_star_rail",
    "honkai3": "honkai_impact_3rd",
    "blda": "blue_archive",
    "mc": "wuthering_waves",
    "zzz": "zenless_zone_zero",
    "cbjq": "snowbreak",
    "ht": "tower_of_fantasy",
}

KEYWORD_GAME_MAP = {
    "1_genshin_chinese_spider_img_keyword.txt": "genshin",
    "3_star_rail_chinese_spider_img_keyword.txt": "star_rail",
    "6_honkai3_chinese_spider_img_keyword.txt": "honkai3",
    "blda_spider_img_keyword.txt": "blda",
    "mc_spider_img_keyword.txt": "mc",
    "zzz_spider_img_keyword.txt": "zzz",
    "cbjq_spider_img_keyword.txt": "cbjq",
    "ht_spider_img_keyword.txt": "ht",
    "qlwh_spider_img_keyword.txt": None,
    "ll_spider_img_keyword.txt": None,
    "lsxy_spider_img_keyword.txt": None,
    "0307_spider_img_keyword.txt": None,
    "1_p_top_spider_img_keyword.txt": None,
    "new_spider_img_keyword.txt": None,
    "spider_img_keyword.txt": None,
}

CHARACTER_MAP = {
    "琴": "jean_(genshin_impact)",
    "安柏": "amber_(genshin_impact)",
    "丽莎": "lisa_(genshin_impact)",
    "芭芭拉": "barbara_(genshin_impact)",
    "可莉": "klee_(genshin_impact)",
    "诺艾尔": "noelle_(genshin_impact)",
    "菲谢尔": "fischl_(genshin_impact)",
    "砂糖": "sucrose_(genshin_impact)",
    "莫娜": "mona_(genshin_impact)",
    "迪奥娜": "diona_(genshin_impact)",
    "罗莎莉亚": "rosaria_(genshin_impact)",
    "优菈": "eula_(genshin_impact)",
    "闲云": "xianyun_(genshin_impact)",
    "瑶瑶": "yaoyao_(genshin_impact)",
    "夜兰": "yelan_(genshin_impact)",
    "申鹤": "shenhe_(genshin_impact)",
    "云堇": "yunjin_(genshin_impact)",
    "北斗": "beidou_(genshin_impact)",
    "凝光": "ningguang_(genshin_impact)",
    "香菱": "xiangling_(genshin_impact)",
    "刻晴": "keqing_(genshin_impact)",
    "七七": "qiqi_(genshin_impact)",
    "辛焱": "xinyan_(genshin_impact)",
    "甘雨": "ganyu_(genshin_impact)",
    "胡桃": "hu_tao_(genshin_impact)",
    "烟绯": "yanfei_(genshin_impact)",
    "神里绫华": "ayaka_(genshin_impact)",
    "宵宫": "yoimiya_(genshin_impact)",
    "早柚": "sayu_(genshin_impact)",
    "雷电将军": "raiden_shogun_(genshin_impact)",
    "八重神子": "yae_miko_(genshin_impact)",
    "九条裟罗": "kujou_sara_(genshin_impact)",
    "珊瑚宫心海": "kokomi_(genshin_impact)",
    "娜维娅": "navia_(genshin_impact)",
    "芙宁娜": "furina_(genshin_impact)",
    "千织": "chiori_(genshin_impact)",
    "久岐忍": "kuki_shinobu_(genshin_impact)",
    "珐露珊": "faruzan_(genshin_impact)",
    "莱依拉": "layla_(genshin_impact)",
    "妮露": "nilou_(genshin_impact)",
    "坎蒂丝": "candace_(genshin_impact)",
    "多莉": "dori_(genshin_impact)",
    "柯莱": "collei_(genshin_impact)",
    "绮良良": "kirara_(genshin_impact)",
    "纳西妲": "nahida_(genshin_impact)",
    "迪希雅": "dehya_(genshin_impact)",
    "迪娜泽黛": "dunyarzad_(genshin_impact)",
    "派蒙": "paimon_(genshin_impact)",
    "夏沃蕾": "chevreuse_(genshin_impact)",
    "夏洛蒂": "charlotte_(genshin_impact)",
    "琳妮特": "lynette_(genshin_impact)",
    "希格雯": "sigewinne_(genshin_impact)",
    "克洛琳德": "clorinde_(genshin_impact)",
    "荧": "lumine_(genshin_impact)",
    "莉奈娅": "lyney_(genshin_impact)",
    "玛拉妮": "mualani_(genshin_impact)",
    "卡齐娜": "kachina_(genshin_impact)",
    "希诺宁": "xilonen_(genshin_impact)",
    "玛薇卡": "mavuika_(genshin_impact)",
    "伊涅芙": "inefuu_(genshin_impact)",
    "菈乌玛": "la_uma_(genshin_impact)",
    "爱诺": "aino_(genshin_impact)",
    "奈芙尔": "nefer_(genshin_impact)",
    "雅珂达": "yakoda_(genshin_impact)",
    "哥伦比娅": "columbina_(genshin_impact)",
    "桑多涅": "sandrone_(genshin_impact)",
    "尼可": "nico_(genshin_impact)",
    "归终": "guizhong_(genshin_impact)",
    "留云借风真君": "xianyun_(genshin_impact)",
    "歌尘浪市真君": "ping_(genshin_impact)",
    "埃洛伊": "aloy_(horizon_zero_dawn)",
    "艾丝妲": "asta_(honkai:_star_rail)",
    "三月七": "march_7th_(honkai:_star_rail)",
    "希露瓦": "serval_(honkai:_star_rail)",
    "黑塔": "herta_(honkai:_star_rail)",
    "大丽花": "dahli_(honkai:_star_rail)",
    "银狼": "silver_wolf_(honkai:_star_rail)",
    "希儿": "seele_(honkai:_star_rail)",
    "卡芙卡": "kafka_(honkai:_star_rail)",
    "素裳": "sushang_(honkai:_star_rail)",
    "姬子": "himeko_(honkai:_star_rail)",
    "布洛妮娅": "bronya_(honkai:_star_rail)",
    "克拉拉": "clara_(honkai:_star_rail)",
    "佩拉": "pela_(honkai:_star_rail)",
    "虎克": "hook_(honkai:_star_rail)",
    "黑天鹅": "black_swan_(honkai:_star_rail)",
    "花火": "sparkle_(honkai:_star_rail)",
    "阮梅": "ruan_mei_(honkai:_star_rail)",
    "娜塔莎": "natasha_(honkai:_star_rail)",
    "寒鸦": "hanya_(honkai:_star_rail)",
    "镜流": "jingliu_(honkai:_star_rail)",
    "雪衣": "xueyi_(honkai:_star_rail)",
    "黄泉": "acheron_(honkai:_star_rail)",
    "符玄": "fu_xuan_(honkai:_star_rail)",
    "白露": "bailu_(honkai:_star_rail)",
    "霍霍": "huohuo_(honkai:_star_rail)",
    "玲妮": "lynx_(honkai:_star_rail)",
    "青雀": "qingque_(honkai:_star_rail)",
    "停云": "tingyun_(honkai:_star_rail)",
    "托帕": "topaz_(honkai:_star_rail)",
    "驭空": "yukong_(honkai:_star_rail)",
    "流萤": "firefly_(honkai:_star_rail)",
    "知更鸟": "robin_(honkai:_star_rail)",
    "缇宝": "tribbie_(honkai:_star_rail)",
    "真珠": "pearl_(honkai:_star_rail)",
    "火花": "sparkle_(honkai:_star_rail)",
    "云璃": "yunli_(honkai:_star_rail)",
    "阿格莱雅": "aglaea_(honkai:_star_rail)",
    "遐蝶": "castorice_(honkai:_star_rail)",
    "刻律德菈": "keller_(honkai:_star_rail)",
    "赛飞儿": "sapphire_(honkai:_star_rail)",
    "昔涟": "cyrene_(honkai:_star_rail)",
    "风堇": "husband_(honkai:_star_rail)",
    "海瑟音": "hester_(honkai:_star_rail)",
    "绯英": "scarlet_(honkai:_star_rail)",
    "虚照": "void_(honkai:_star_rail)",
    "翡翠": "jade_(honkai:_star_rail)",
    "布洛妮娅·扎伊切克": "bronya_(honkai_impact_3rd)",
    "无量塔姬子": "himeko_(honkai_impact_3rd)",
    "八重樱": "yae_sakura_(honkai_impact_3rd)",
    "德丽莎·阿波卡利斯": "theresa_(honkai_impact_3rd)",
    "卡莲·卡斯兰娜": "kallen_(honkai_impact_3rd)",
    "丽塔·洛丝薇瑟": "rita_(honkai_impact_3rd)",
    "希儿·芙乐艾": "seele_(honkai_impact_3rd)",
    "萝莎莉娅·阿琳": "rozaliya_(honkai_impact_3rd)",
    "莉莉娅·阿琳": "liliya_(honkai_impact_3rd)",
    "时雨绮罗": "shigure_kira_(honkai_impact_3rd)",
    "普罗米修斯": "prometheus_(honkai_impact_3rd)",
    "米丝忒琳·沙尼亚特": "misteln_(honkai_impact_3rd)",
    "苏莎娜": "susannah_(honkai_impact_3rd)",
    "爱衣·休伯利安Λ": "ai_(honkai_impact_3rd)",
    "李素裳": "li_sushang_(honkai_impact_3rd)",
    "维尔薇": "vill-v_(honkai_impact_3rd)",
    "梅比乌斯": "mobius_(honkai_impact_3rd)",
    "帕朵菲莉丝": "pardofelis_(honkai_impact_3rd)",
    "阿波尼亚": "aponia_(honkai_impact_3rd)",
    "伊甸": "eden_(honkai_impact_3rd)",
    "比安卡·幽兰黛尔·阿塔吉娜": "biana_youlandeier_altjina_(honkai_impact_3rd)",
    "式波·明日香·兰格雷": "asuka_langley_(honkai_impact_3rd)",
    "娜塔莎·希奥拉": "natasha_ciora_(honkai_impact_3rd)",
    "卡萝尔·佩珀": "carol_pepper_(honkai_impact_3rd)",
    "符华": "fu_hua_(honkai_impact_3rd)",
    "格蕾修": "griseo_(honkai_impact_3rd)",
    "爱莉希雅": "elysia_(honkai_impact_3rd)",
    "琪亚娜": "kiana_(honkai_impact_3rd)",
    "雷电芽衣": "raiden_mei_(honkai_impact_3rd)",
    "识之律者": "herrscher_of_sentience_(honkai_impact_3rd)",
    "雷之律者": "herrscher_of_thunder_(honkai_impact_3rd)",
    "空之律者": "herrscher_of_the_void_(honkai_impact_3rd)",
    "死生之律者": "herrscher_of_death_(honkai_impact_3rd)",
    "薪炎之律者": "herrscher_of_flamescion_(honkai_impact_3rd)",
    "始源之律者": "herrscher_of_origin_(honkai_impact_3rd)",
    "人之律者": "herrscher_of_human_(honkai_impact_3rd)",
    "幽兰黛尔": "durandal_(honkai_impact_3rd)",
    "阿洛娜": "arona_(blue_archive)",
    "普拉娜": "plana_(blue_archive)",
    "日奈": "hina_(blue_archive)",
    "亚子": "ako_(blue_archive)",
    "伊织": "iori_(blue_archive)",
    "千夏": "chinatsu_(blue_archive)",
    "伊吕波": "iroha_(blue_archive)",
    "阿露": "aru_(blue_archive)",
    "睦月": "mutsuki_(blue_archive)",
    "佳代子": "kayoko_(blue_archive)",
    "遥香": "haruka_(blue_archive)",
    "晴奈": "haruna_(blue_archive)",
    "淳子": "junko_(blue_archive)",
    "明里": "akari_(blue_archive)",
    "泉": "izumi_(blue_archive)",
    "枫香": "fuuka_(blue_archive)",
    "朱莉": "juri_(blue_archive)",
    "濑名": "sena_(blue_archive)",
    "惠": "megumi_(blue_archive)",
    "霞": "kasumi_(blue_archive)",
    "优香": "yuuka_(blue_archive)",
    "诺亚": "noa_(blue_archive)",
    "小雪": "koyuki_(blue_archive)",
    "尼禄": "neru_(blue_archive)",
    "明日奈": "asuna_(blue_archive)",
    "花凛": "karin_(blue_archive)",
    "朱音": "akane_(blue_archive)",
    "时": "toki_(blue_archive)",
    "歌原": "utaha_(blue_archive)",
    "响": "hibiki_(blue_archive)",
    "柯托莉": "kotori_(blue_archive)",
    "柚子": "yuzu_(blue_archive)",
    "桃井": "momoi_(blue_archive)",
    "绿": "midori_(blue_archive)",
    "爱丽丝": "aris_(blue_archive)",
    "千寻": "chihiro_(blue_archive)",
    "真纪": "maki_(blue_archive)",
    "晴": "haru_(blue_archive)",
    "小玉": "kotama_(blue_archive)",
    "日鞠": "hifumi_(blue_archive)",
    "艾米": "emi_(blue_archive)",
    "菫": "sumire_(blue_archive)",
    "未花": "mika_(blue_archive)",
    "渚": "nagisa_(blue_archive)",
    "鹤城": "hoshino_(blue_archive)",
    "小鸟游星野": "hoshino_(blue_archive)",
    "空崎日奈": "hina_(blue_archive)",
    "鬼方佳代子": "kayoko_(blue_archive)",
    "早濑优香": "yuuka_(blue_archive)",
    "天雨亚子": "ako_(blue_archive)",
    "陆八魔爱露": "aru_(blue_archive)",
    "圣园未花": "mika_(blue_archive)",
    "天童爱丽丝": "aris_(blue_archive)",
    "杏山和纱": "kazusa_(blue_archive)",
    "砂狼白子": "shiroko_(blue_archive)",
    "一之濑明日奈": "asuna_(blue_archive)",
    "秧秧": "yangyang_(wuthering_waves)",
    "安可": "encore_(wuthering_waves)",
    "炽霞": "chixia_(wuthering_waves)",
    "丹瑾": "danjin_(wuthering_waves)",
    "白芷": "baizhi_(wuthering_waves)",
    "散华": "sanhua_(wuthering_waves)",
    "维里奈": "verina_(wuthering_waves)",
    "今汐": "jinhsi_(wuthering_waves)",
    "长离": "changli_(wuthering_waves)",
    "吟霖": "yinlin_(wuthering_waves)",
    "漂泊者": "rover_(wuthering_waves)",
    "桃祈": "taoqi_(wuthering_waves)",
    "鉴心": "jianxin_(wuthering_waves)",
    "卡提希娅": "carthya_(wuthering_waves)",
    "爱弥斯": "aix_(wuthering_waves)",
    "绯雪": "feixue_(wuthering_waves)",
    "洛可可": "roccoco_(wuthering_waves)",
    "菲比": "fifi_(wuthering_waves)",
    "珂莱塔": "carlotta_(wuthering_waves)",
    "釉瑚": "youhu_(wuthering_waves)",
    "莫宁": "moning_(wuthering_waves)",
    "洛瑟拉": "roscella_(wuthering_waves)",
    "琳奈": "linne_(wuthering_waves)",
    "守岸人": "shorekeeper_(wuthering_waves)",
    "达妮娅": "dania_(wuthering_waves)",
    "西格莉卡": "siglika_(wuthering_waves)",
    "丽贝卡": "rebecca_(wuthering_waves)",
    "露西": "lucy_(wuthering_waves)",
    "弗洛洛": "phrololo_(wuthering_waves)",
    "嘉贝莉娜": "gabriel_(wuthering_waves)",
    "奥古斯塔": "augusta_(wuthering_waves)",
    "尤诺": "yuno_(wuthering_waves)",
    "赞妮": "zani_(wuthering_waves)",
    "坎特蕾拉": "cantarella_(wuthering_waves)",
    "露帕": "lupa_(wuthering_waves)",
    "夏空": "xiakong_(wuthering_waves)",
    "椿": "tsubaki_(wuthering_waves)",
    "灯灯": "dengdeng_(wuthering_waves)",
    "铃": "ring_(zenless_zone_zero)",
    "零号": "zero_(zenless_zone_zero)",
    "猫宫又奈": "nekomiya_(zenless_zone_zero)",
    "猫又": "nekomata_(zenless_zone_zero)",
    "妮可·德玛拉": "nicole_(zenless_zone_zero)",
    "格莉丝·霍华德": "grace_(zenless_zone_zero)",
    "珂蕾妲·贝洛伯格": "koleda_(zenless_zone_zero)",
    "柏妮思·怀特": "burnice_(zenless_zone_zero)",
    "凯撒·金": "caesar_(zenless_zone_zero)",
    "莱特": "lycaon_(zenless_zone_zero)",
    "派派·韦尔": "piper_(zenless_zone_zero)",
    "波可娜·费雷尼": "pomona_(zenless_zone_zero)",
    "雨果·维拉德": "hugo_(zenless_zone_zero)",
    "薇薇安·班希": "vivian_(zenless_zone_zero)",
    "爱丽丝·泰姆菲尔德": "alice_(zenless_zone_zero)",
    "狛野真斗": "...(zenless_zone_zero)",
    "卢西娅·艾洛温": "lucia_(zenless_zone_zero)",
    "浮波柚叶": "...(zenless_zone_zero)",
    "伊德海莉·墨菲": "yideli_(zenless_zone_zero)",
    "爱芮": "erii_(zenless_zone_zero)",
    "南宫羽": "mikuni_(zenless_zone_zero)",
    "千夏": "chinatsu_(zenless_zone_zero)",
    "亚历山德丽娜·莎芭丝缇安": "alexandrina_(zenless_zone_zero)",
    "可琳·威克斯": "corin_(zenless_zone_zero)",
    "艾莲·乔": "ellen_(zenless_zone_zero)",
    "冯·莱卡恩": "von_lycaon_(zenless_zone_zero)",
    "简·杜": "jane_(zenless_zone_zero)",
    "青衣": "qingyi_(zenless_zone_zero)",
    "赛斯·洛威尔": "seth_(zenless_zone_zero)",
    "朱鸢": "zhu_yuan_(zenless_zone_zero)",
    "星见雅": "yanagi_(zenless_zone_zero)",
    "苍角": "sokaku_(zenless_zone_zero)",
    "月城柳": "yanagi_(zenless_zone_zero)",
    "奥菲丝": "anby_(zenless_zone_zero)",
    "11号": "soldier_11_(zenless_zone_zero)",
    "扳机": "trigger_(zenless_zone_zero)",
    "橘福福": "...(zenless_zone_zero)",
    "潘引壶": "...(zenless_zone_zero)",
    "叶瞬光": "...(zenless_zone_zero)",
    "仪玄": "...(zenless_zone_zero)",
    "般岳": "...(zenless_zone_zero)",
    "琉音": "...(zenless_zone_zero)",
    "希希芙": "...(zenless_zone_zero)",
    "妮塔": "nita_(snowbreak)",
    "肴": "yao_(snowbreak)",
    "瑟瑞斯": "seres_(snowbreak)",
    "苔丝·科特金": "tess_(snowbreak)",
    "芙提雅-缄默": "fritia_(snowbreak)",
    "肴-冬至": "yao_(snowbreak)",
    "鸣濑晴": "haru_(snowbreak)",
    "晴-藏锋": "haru_(snowbreak)",
    "辰星-云篆": "chenxing_(snowbreak)",
    "凯茜娅·克莱因": "kasia_(snowbreak)",
    "茉莉安·安德烈奥蒂": "mariya_(snowbreak)",
    "芬妮·戈尔登": "fenni_(snowbreak)",
    "琴诺": "qin_(snowbreak)",
    "安卡希雅": "ankaxiya_(snowbreak)",
    "里芙": "lifu_(snowbreak)",
    "伊切尔·豹豹": "yichier_(snowbreak)",
    "凯茜娅·蓝闪": "kasia_(snowbreak)",
    "辰星": "chenxing_(snowbreak)",
    "恩雅": "enya_(snowbreak)",
    "芬妮·咎冠": "fenni_(snowbreak)",
    "猫汐尔·溯影": "maoxier_(snowbreak)",
    "猫汐尔": "maoxier_(snowbreak)",
    "夏佐": "xiazao_(tower_of_fantasy)",
    "莎莉": "shali_(tower_of_fantasy)",
    "梅丽尔": "meriel_(tower_of_fantasy)",
    "赛弥尔": "samir_(tower_of_fantasy)",
    "艾莉丝": "alice_(tower_of_fantasy)",
    "奈美西斯": "nemesis_(tower_of_fantasy)",
    "蕾贝": "rube_(tower_of_fantasy)",
    "菲欧娜": "fiona_(tower_of_fantasy)",
    "卡洛琳": "caroline_(tower_of_fantasy)",
    "伊卡洛斯": "icarus_(tower_of_fantasy)",
    "可可丽特": "cocoritter_(tower_of_fantasy)",
    "凛夜": "linye_(tower_of_fantasy)",
    "白伶": "bailing_(tower_of_fantasy)",
    "克劳迪娅": "claudia_(tower_of_fantasy)",
    "海拉": "haila_(tower_of_fantasy)",
    "伊蕾娜": "yilena_(tower_of_fantasy)",
    "薇拉": "vera_(tower_of_fantasy)",
    "弗丽嘉": "frigg_(tower_of_fantasy)",
    "赛琳娜": "serena_(tower_of_fantasy)",
    "修玛": "huma_(tower_of_fantasy)",
    "芬璃尔": "fenrir_(tower_of_fantasy)",
    "初音未来": "hatsune_miku",
    "芙莉莲": "frieren_(sousou_no_frieren)",
    "菲伦": "fern_(sousou_no_frieren)",
    "尤贝尔": "uvel_(sousou_no_frieren)",
    "博丽灵梦": "hakurei_reimu",
    "雾雨魔理沙": "marisa_kirisame",
    "芙兰朵露": "frandre_scarlet",
    "古明地恋": "komeiji_koishi",
    "后藤一里": "gouto_hitori_(bocchi_the_rock)",
    "星街彗星": "hoshimachi_suisei",
    "宝钟玛琳": "houshou_marine",
    "小埋": "umaru_(himouto!_umaru-chan)",
    "干物妹": "umaru_(himouto!_umaru-chan)",
    "工作细胞血小板": "platelet_(hataraku_saibou)",
    "蕾姆": "rem_(re:zero)",
    "拉姆": "ram_(re:zero)",
    "犬饲小麦": "inu_kogal",
    "佩佩": "pepe_(love_live)",
    "诺诺": "nono_(love_live)",
    "忒拉拉": "telara_(love_live)",
    "寒悠悠": "han_youyou_(love_live)",
    "夏儿": "xiar_(love_live)",
    "洛卿": "luoqing_(love_live)",
    "朝武芳乃": "yoshino_(k_o_u_s_h_i_k_i)",
    "常陆茉子": "maiko_(k_o_u_s_h_i_k_i)",
}


def read_all_characters():
    """从 keywords 目录读取所有角色名"""
    all_characters = {}
    
    for keyword_file in KEYWORD_DIR.glob("*.txt"):
        if keyword_file.name not in KEYWORD_GAME_MAP:
            continue
        
        game_key = KEYWORD_GAME_MAP[keyword_file.name]
        game_tag = GAME_TAG_MAP.get(game_key) if game_key else None
        
        try:
            with open(keyword_file, 'r', encoding='utf-8') as f:
                lines = f.readlines()
            
            for line in lines:
                name = line.strip()
                if name and name not in all_characters:
                    all_characters[name] = {
                        'source_file': keyword_file.name,
                        'game_key': game_key,
                        'game_tag': game_tag,
                        'danbooru_tag': CHARACTER_MAP.get(name, "")
                    }
        except Exception as e:
            print(f"读取 {keyword_file.name} 失败: {e}")
    
    return all_characters


def generate_config():
    """生成配置文件"""
    all_characters = read_all_characters()
    
    config = {
        'game_tag_map': GAME_TAG_MAP,
        'keyword_game_map': KEYWORD_GAME_MAP,
        'character_map': CHARACTER_MAP,
        'all_characters': all_characters,
        'generated_at': str(Path(__file__).parent.parent.parent.parent / "archived" / "auto_spider_img" / "keywords"),
        'total_characters': len(all_characters),
        'total_mapped': sum(1 for c in all_characters.values() if c['danbooru_tag']),
    }
    
    output_path = CONFIG_DIR / "collection_config.json"
    with open(output_path, 'w', encoding='utf-8') as f:
        json.dump(config, f, ensure_ascii=False, indent=2)
    
    print(f"配置文件已生成: {output_path}")
    print(f"总角色数: {len(all_characters)}")
    print(f"已映射角色数: {sum(1 for c in all_characters.values() if c['danbooru_tag'])}")
    print(f"未映射角色数: {sum(1 for c in all_characters.values() if not c['danbooru_tag'])}")
    
    return config


if __name__ == "__main__":
    generate_config()