ARG REGISTRY_MIRROR=docker.io
ARG BASE_IMAGE=ard-base
FROM ${BASE_IMAGE}

COPY .env.example .env
COPY src/ ./src/

RUN mkdir -p logs run

RUN pip install Pillow

CMD ["python", "src/services/search_service/search_worker.py"]
