ARG REGISTRY_MIRROR=docker.io
FROM ${REGISTRY_MIRROR}/library/node:18 AS builder

WORKDIR /app

ARG NPM_CONFIG_REGISTRY=https://registry.npmmirror.com/
ENV NPM_CONFIG_REGISTRY=${NPM_CONFIG_REGISTRY}

COPY src/frontend/package.json ./
COPY src/frontend/package-lock.json ./

RUN npm ci --legacy-peer-deps

COPY src/frontend/ ./

RUN npm run build

ARG REGISTRY_MIRROR
FROM ${REGISTRY_MIRROR}/library/nginx:alpine

COPY deployment/nginx.conf /etc/nginx/nginx.conf
COPY --from=builder /app/out /usr/share/nginx/html

EXPOSE 3000

CMD ["nginx", "-g", "daemon off;"]
