FROM node:18-alpine AS builder

WORKDIR /app

COPY src/frontend/package.json ./
COPY src/frontend/package-lock.json ./

RUN npm ci

COPY src/frontend/ ./

RUN npm run build

FROM nginx:alpine

COPY deployment/nginx.conf /etc/nginx/nginx.conf
COPY --from=builder /app/out /usr/share/nginx/html

EXPOSE 3000

CMD ["nginx", "-g", "daemon off;"]
