ARG REGISTRY_MIRROR=docker.io
ARG BASE_IMAGE=ard-base
FROM ${BASE_IMAGE}

RUN apt-get update && apt-get install -y --no-install-recommends \
    ffmpeg \
    && rm -rf /var/lib/apt/lists/*

COPY .env.example .env
COPY src/ ./src/

RUN mkdir -p logs run

EXPOSE 8000

CMD ["python", "src/services/multimedia_service/multimedia_service_app.py"]
