ARG REGISTRY_MIRROR=docker.io
FROM ${REGISTRY_MIRROR}/library/node:20 AS builder

WORKDIR /app

ARG NPM_CONFIG_REGISTRY=https://registry.npmmirror.com/
ENV NPM_CONFIG_REGISTRY=${NPM_CONFIG_REGISTRY}

COPY src/frontend/package.json ./
COPY src/frontend/package-lock.json ./

RUN rm -rf node_modules package-lock.json && npm install --legacy-peer-deps

COPY src/frontend/ ./

RUN npm run build

ARG REGISTRY_MIRROR
FROM ${REGISTRY_MIRROR}/library/node:20-slim

WORKDIR /app

COPY --from=builder /app/.next/standalone ./
COPY --from=builder /app/.next/static ./.next/static

EXPOSE 3000

CMD ["node", "server.js"]
