ARG REGISTRY_MIRROR=docker.io
ARG BASE_IMAGE=ardc/base:latest
FROM ${BASE_IMAGE}

COPY .env.example .env
COPY src/ ./src/

RUN mkdir -p logs run

EXPOSE 8003

CMD ["python", "src/services/search_service/app_queue.py"]
