ARG REGISTRY_MIRROR=docker.io
ARG BASE_IMAGE=ardc/ml-base:latest
FROM ${BASE_IMAGE}

COPY .env.example .env
COPY src/ ./src/

RUN mkdir -p logs run

CMD ["python", "src/services/inference_worker/worker.py", "--num-workers", "2", "--model", "ViT-B/32"]
