ARG REGISTRY_MIRROR=docker.io
ARG BASE_IMAGE=ardc/base:latest
FROM ${BASE_IMAGE}

RUN sed -i 's/deb.debian.org/mirrors.aliyun.com/g' /etc/apt/sources.list.d/debian.sources

RUN apt-get update && apt-get install -y --no-install-recommends \
    ffmpeg \
    && rm -rf /var/lib/apt/lists/*

COPY .env.example .env
COPY src/ ./src/

RUN mkdir -p logs run

EXPOSE 8000

CMD ["python", "src/services/multimedia_service/multimedia_service_app.py"]
